version: '1.0'
services:
  backend:
    container_name: chargepal-demo-be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      POSTGRES_DB: chargepal_app_dev
      POSTGRES_HOST: dockerPostgres
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 
      POSTGRES_PORT: 5435
      JWT_SECRET_KEY: 
      API_SECRET_KEY: 
      RPC_URL: 
      CHARGE_TOKEN_ADDRESS:
      ORACLE_API:
      ORACLE_KEY:
      EM_USERNAME:
      EM_PASSWORD:

  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: dockerPostgres
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - '5435:5435'
    environment:
      - POSTGRES_DB=go_app_dev
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=
    command: -p 5435

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    container_name: dockerRedis
